### ISSUE TITLE
New API wrapping the drivers

### ISSUE THREAD

**Issue by synw** [centrifugal/centrifuge-go#13]
Hi. I have designed an API that wraps both Centrifugo's client and server drivers: its [here](https://github.com/synw/centcom).

I did not separate the server and client drivers: its all embedded in one structure. This is because I use them both together, usually in server to server or cli to server communications where both parts have the Centrifugo secret key, so that I can use http to send messages in any channel without having to change the Centrifugo's configuration. 
I really don't know how the people use these go drivers but I feel that the client/server paradigm does not fit well here, so I separated by transport protocol. Is there anything wrong with this approach?

I am currently testing it and it appears that the client drivers wrapping significantly saves me some time. The server API is just fine, so I embedded it as is.

All test feedback is welcome. About the code: I am a rookie in go so it might be clumsy for some parts (but show no mercy if you check it out :)

**Comment by FZambia** [comment]
@synw glad you finished this! 

As I said before I need some time to finish work on `centrifuge-mobile` and think about what to do with this client - change API accordingly or redirect users to `centrifuge-mobile`, maybe I'll try to create one shared code core for both - still thinking around.

Will look at your library and come back with feedback, thanks 👍
