### ISSUE TITLE
stable for production?

### ISSUE THREAD

**Issue by anshumanr** [centrifugal/centrifuge-go#26]
Hi,
Didn't have a better place to ask this, but can we consider this go library for Centrifugo stable for production use?

Will appreciate a response. Thanks.

**Comment by FZambia** [comment]
@anshumanr hello, personally I am currently using this client for benchmark stand of Centrifuge library generating 1 million connections with it, subscribing to 2 million channels, publishing about 600k messages per minute. In general this means that client is stable enough. Though this also means that my personal usage of this client is very limited so there could be problems I don't know about.

You still need to use it with strict versioning as it does not have v1 release.

**Comment by anshumanr** [comment]
Alright. Thanks for the feedback.
