### ISSUE TITLE
Test cases without a separate server

### ISSUE THREAD

**Issue by logrusorgru** [centrifugal/centrifuge-go#27]
Hi, I want to write test cases without a separate server. Creating server in the test cases. But, it's impossible, because of protocol buffers registering. The `centrifuge-go` and the `centrifuge` ('la server) registers the same proto types. And this produce a panicking. Thus, it's impossible to import and make them work together.

Can yo please move the proto files to a separate package imported by both `centrifuge-go` and `centrifuge`.

Also, it there a way to provide a fake connection, instead of a real listening. For example, NATS allows to provide own Dialer to create fake connections (based on a pipe or buffer) for tests.

**Comment by FZambia** [comment]
@logrusorgru hello, can you provide an example of panic and and example of Nats Dialer?

**Comment by logrusorgru** [comment]
Hi, just import

```go
package main

import (
	_ "github.com/centrifugal/centrifuge"
	_ "github.com/centrifugal/centrifuge-go"
)

func main() {}
```

It's about gogo/protobuf initialization.

**Comment by logrusorgru** [comment]
Nats allows to run server inside test cases without, for example https://github.com/nats-io/nats.go/issues/467#issuecomment-494610877

**Comment by logrusorgru** [comment]
The problem.

There is the same proto types in this package and in the github.com/centrifugal/centrifuge. For example

1. https://github.com/centrifugal/centrifuge/blob/master/misc/proto/client.gogo.proto#L18
2. https://github.com/centrifugal/centrifuge-go/blob/master/internal/proto/client.proto#L18

Both register this proto types. And the gogo/protobuf produce panic because of double-registering. Also, the gogo/protobuf panics only on enums, but has TODO note about messages

- https://github.com/gogo/protobuf/blob/master/proto/properties.go#L547

---

The proto messages moved to a separate package will be initialized once, even if they are imported by many packages. But, as I understood, there is different set of messages for server and client. That makes this work not so trivial.

**Comment by FZambia** [comment]
Thanks, yeah, I see now.

I made a quick experiment trying to rename package that contains generated files to see whether this fix a problem. So instead of registering `proto.PushType` it becomes for example `clientproto.PushType`. It does! But it requires changing package name (`proto` -> `clientproto`) when copying our main Protobuf definitions that live in Centrifuge library repo to centrifuge-go client library.

Simply modifying package name via protoc command:

```diff
diff --git a/misc/generate.sh b/misc/generate.sh
index fcb3fb1..4be1ce9 100755
--- a/misc/generate.sh
+++ b/misc/generate.sh
@@ -1,3 +1,3 @@
 #!/bin/bash
 cp $GOPATH/src/github.com/centrifugal/centrifuge/misc/proto/client.gogo.proto internal/proto/client.proto
-cd internal/proto && protoc --proto_path=$GOPATH/src:$GOPATH/src/github.com/centrifugal/centrifuge-go/vendor:. --gogofaster_out=. client.proto
+cd internal/proto && protoc --proto_path=$GOPATH/src:$GOPATH/src/github.com/centrifugal/centrifuge-go/vendor:. --gogofaster_out=import_path=clientproto:. client.proto
```

– does not work unfortunately as generated code continues to have `proto.X` registrations. 

I suppose moving definitions to separate package makes sense in this case. I thought about doing this before but could not find enough reasoning over simply generating code separately. As you properly pointed there are some messages that used only on client side and only on server side. Regarding to definitions I don't think this is a big problem, but we also have some helpers around generated definitions (encoders, decoders) – can't say at moment what's the correct way to deal with them - keep all in separate new package or keep helpers where they used (some in server code repo, some in client code repo).

**Comment by FZambia** [comment]
I will try to experiment with separate package during this week, my plan is to move client protocol to another package in centrifugal organization - `github.com/centrifugal/protocol`. Then I suppose we can move this lib to use that package. Also I think its a good time to add go mod support to centrifuge-go. At that moment panic should gone away. Next step will be moving Centrifuge library to new protocol package. I also think that all reasonable helper methods and constants will be moved to protocol package. @logrusorgru what do you think?

**Comment by FZambia** [comment]
Pushed v0.3.0 tag of this package, it uses `github.com/centrifugal/protocol` package. Also open [pull request](https://github.com/centrifugal/centrifuge/pull/78) in centrifuge library repo to migrate to this package too.

**Comment by FZambia** [comment]
@logrusorgru hello, did this solve your case?

**Comment by logrusorgru** [comment]
@FZambia, sorry for the late replay. I didn't have enough time to write a test case.

Yes, it resolves the case. Now I can use unit tests for my applications putting a server inside a unit-test file. Making them go-testable with a good coverage, without mocks, without a separate server, etc, etc. Lots of opportunities.

Thank you, for your work.

For example (server-related code is only about 40 lines):

```go
package main

import (
	"context"
	"encoding/json"
	"net"
	"net/http"
	"sync"
	"testing"
	"time"

	server "github.com/centrifugal/centrifuge"
	client "github.com/centrifugal/centrifuge-go"
)

// start centrifuge test server
func newTestServer(t *testing.T) (addr string, cancel func()) {
	t.Helper()

	var conf = server.DefaultConfig
	conf.ClientInsecure = true
	conf.Publish = true
	var node, err = server.New(conf)
	if err != nil {
		t.Fatal(err)
	}
	if err = node.Run(); err != nil {
		t.Fatal(err)
	}

	var mux = http.NewServeMux()
	mux.Handle("/connection/websocket", server.NewWebsocketHandler(node,
		server.WebsocketConfig{}))

	var l net.Listener
	if l, err = net.Listen("tcp", "127.0.0.1:0"); err != nil {
		t.Fatal(err)
	}

	var s http.Server
	s.Handler = mux
	go s.Serve(l)

	// stop server and listener
	cancel = func() {
		node.Shutdown(context.Background())
		l.Close()
	}

	return l.Addr().String(), cancel
}

func Test(t *testing.T) {

	const (
		subj    = "subject"
		timeout = 100 * time.Millisecond
		message = "hello!"
	)

	var addr, cancel = newTestServer(t)
	defer cancel()

	var (
		send, recv = make(chan string), make(chan string)
		quit       = make(chan struct{})
		wg         sync.WaitGroup
	)

	wg.Add(2)
	go sending(t, &wg, addr, subj, send)
	go receiving(t, &wg, addr, subj, recv, quit)

	defer wg.Wait()

	defer close(quit)
	defer close(send)

	select {
	case send <- message:
	case <-time.After(timeout):
		t.Fatal("sending timeout")
	}

	select {
	case val := <-recv:
		if val != message {
			t.Error("unexpected message received:", message)
		}
	case <-time.After(timeout):
	}

}

type data struct {
	Value string `json:"value"`
}

func marshal(t *testing.T, val string) []byte {
	var d data
	d.Value = val
	b, err := json.Marshal(&d)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func unmarshal(t *testing.T, b []byte) string {
	var (
		d   data
		err = json.Unmarshal(b, &d)
	)
	if err != nil {
		t.Fatal(err)
	}
	return d.Value
}

func sending(t *testing.T, wg *sync.WaitGroup, addr string, subj string,
	send <-chan string) {

	defer wg.Done()

	var (
		conf = client.DefaultConfig()
		conn = client.New("ws://"+addr+"/connection/websocket", conf)
		err  error
	)
	defer conn.Close()
	if err = conn.Connect(); err != nil {
		t.Fatal(err)
	}
	defer conn.Close()
	for {
		val, ok := <-send
		if !ok {
			return
		}
		err = conn.Publish(subj, marshal(t, val))
		if err != nil {
			t.Error(err)
		}
	}
}

type handler struct {
	t    *testing.T
	recv chan<- string
}

func (h *handler) OnPublish(s *client.Subscription, pe client.PublishEvent) {
	select {
	case h.recv <- unmarshal(h.t, pe.Data):
	default:
		h.t.Error("channel is not receiving")
	}
}

func receiving(t *testing.T, wg *sync.WaitGroup, addr string, subj string,
	recv chan<- string, quit <-chan struct{}) {

	defer wg.Done()

	var (
		conf = client.DefaultConfig()
		conn = client.New("ws://"+addr+"/connection/websocket", conf)
		err  error
	)
	defer conn.Close()

	if err = conn.Connect(); err != nil {
		t.Fatal(err)
	}

	var sub *client.Subscription
	if sub, err = conn.NewSubscription(subj); err != nil {
		t.Fatal(err)
	}
	defer sub.Unsubscribe()
	sub.OnPublish(&handler{t: t, recv: recv})

	if err = sub.Subscribe(); err != nil {
		t.Fatal(err)
	}

	<-quit
}

```

**Comment by jagadeeshkoka** [comment]
> @FZambia, sorry for the late replay. I didn't have enough time to write a test case.
> 
> Yes, it resolves the case. Now I can use unit tests for my applications putting a server inside a unit-test file. Making them go-testable with a good coverage, without mocks, without a separate server, etc, etc. Lots of opportunities.
> 
> Thank you, for your work.
> 
> For example (server-related code is only about 40 lines):
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"encoding/json"
> 	"net"
> 	"net/http"
> 	"sync"
> 	"testing"
> 	"time"
> 
> 	server "github.com/centrifugal/centrifuge"
> 	client "github.com/centrifugal/centrifuge-go"
> )
> 
> // start centrifuge test server
> func newTestServer(t *testing.T) (addr string, cancel func()) {
> 	t.Helper()
> 
> 	var conf = server.DefaultConfig
> 	conf.ClientInsecure = true
> 	conf.Publish = true
> 	var node, err = server.New(conf)
> 	if err != nil {
> 		t.Fatal(err)
> 	}
> 	if err = node.Run(); err != nil {
> 		t.Fatal(err)
> 	}
> 
> 	var mux = http.NewServeMux()
> 	mux.Handle("/connection/websocket", server.NewWebsocketHandler(node,
> 		server.WebsocketConfig{}))
> 
> 	var l net.Listener
> 	if l, err = net.Listen("tcp", "127.0.0.1:0"); err != nil {
> 		t.Fatal(err)
> 	}
> 
> 	var s http.Server
> 	s.Handler = mux
> 	go s.Serve(l)
> 
> 	// stop server and listener
> 	cancel = func() {
> 		node.Shutdown(context.Background())
> 		l.Close()
> 	}
> 
> 	return l.Addr().String(), cancel
> }
> 
> func Test(t *testing.T) {
> 
> 	const (
> 		subj    = "subject"
> 		timeout = 100 * time.Millisecond
> 		message = "hello!"
> 	)
> 
> 	var addr, cancel = newTestServer(t)
> 	defer cancel()
> 
> 	var (
> 		send, recv = make(chan string), make(chan string)
> 		quit       = make(chan struct{})
> 		wg         sync.WaitGroup
> 	)
> 
> 	wg.Add(2)
> 	go sending(t, &wg, addr, subj, send)
> 	go receiving(t, &wg, addr, subj, recv, quit)
> 
> 	defer wg.Wait()
> 
> 	defer close(quit)
> 	defer close(send)
> 
> 	select {
> 	case send <- message:
> 	case <-time.After(timeout):
> 		t.Fatal("sending timeout")
> 	}
> 
> 	select {
> 	case val := <-recv:
> 		if val != message {
> 			t.Error("unexpected message received:", message)
> 		}
> 	case <-time.After(timeout):
> 	}
> 
> }
> 
> type data struct {
> 	Value string `json:"value"`
> }
> 
> func marshal(t *testing.T, val string) []byte {
> 	var d data
> 	d.Value = val
> 	b, err := json.Marshal(&d)
> 	if err != nil {
> 		t.Fatal(err)
> 	}
> 	return b
> }
> 
> func unmarshal(t *testing.T, b []byte) string {
> 	var (
> 		d   data
> 		err = json.Unmarshal(b, &d)
> 	)
> 	if err != nil {
> 		t.Fatal(err)
> 	}
> 	return d.Value
> }
> 
> func sending(t *testing.T, wg *sync.WaitGroup, addr string, subj string,
> 	send <-chan string) {
> 
> 	defer wg.Done()
> 
> 	var (
> 		conf = client.DefaultConfig()
> 		conn = client.New("ws://"+addr+"/connection/websocket", conf)
> 		err  error
> 	)
> 	defer conn.Close()
> 	if err = conn.Connect(); err != nil {
> 		t.Fatal(err)
> 	}
> 	defer conn.Close()
> 	for {
> 		val, ok := <-send
> 		if !ok {
> 			return
> 		}
> 		err = conn.Publish(subj, marshal(t, val))
> 		if err != nil {
> 			t.Error(err)
> 		}
> 	}
> }
> 
> type handler struct {
> 	t    *testing.T
> 	recv chan<- string
> }
> 
> func (h *handler) OnPublish(s *client.Subscription, pe client.PublishEvent) {
> 	select {
> 	case h.recv <- unmarshal(h.t, pe.Data):
> 	default:
> 		h.t.Error("channel is not receiving")
> 	}
> }
> 
> func receiving(t *testing.T, wg *sync.WaitGroup, addr string, subj string,
> 	recv chan<- string, quit <-chan struct{}) {
> 
> 	defer wg.Done()
> 
> 	var (
> 		conf = client.DefaultConfig()
> 		conn = client.New("ws://"+addr+"/connection/websocket", conf)
> 		err  error
> 	)
> 	defer conn.Close()
> 
> 	if err = conn.Connect(); err != nil {
> 		t.Fatal(err)
> 	}
> 
> 	var sub *client.Subscription
> 	if sub, err = conn.NewSubscription(subj); err != nil {
> 		t.Fatal(err)
> 	}
> 	defer sub.Unsubscribe()
> 	sub.OnPublish(&handler{t: t, recv: recv})
> 
> 	if err = sub.Subscribe(); err != nil {
> 		t.Fatal(err)
> 	}
> 
> 	<-quit
> }
> ```

Does it have any java equivalent example or sample ?

**Comment by logrusorgru** [comment]
> Does it have any java equivalent example or sample ?

@jagadeeshkoka, seems, you have to start Centrifugo server outside a Java code. Because the server written on Golang. In this example it starts the server inside unit tests, because the server is just a Go code. And the unit tests too.
