### ISSUE TITLE
centrifuge.Rpc Always timeout

### ISSUE THREAD

**Issue by ZhuRongJian** [centrifugal/centrifuge-go#30]
r.socket = centrifuge.New(config.SocketUrl, centrifuge.DefaultConfig())
_, err := r.socket.RPC(dataBytes)
	if err != nil {
		fmt.Println(err)
	}

err Always timeout
but service can  Receive message

**Comment by FZambia** [comment]
@ZhuRongJian hi, just checked this locally and can't reproduce – I receive a `Not Available` error if RPC proxy is not registered on server side and a proper response if RPC is registered.

**Comment by ZhuRongJian** [comment]
@FZambia I found out the problem. When I write RPC in time, it will time out

**Comment by FZambia** [comment]
@ZhuRongJian yeah, just [made an example](https://github.com/centrifugal/centrifuge-go/blob/master/examples/rpc/main.go#L25) on how to deal with this.

The reason is that at moment registered callbacks called from the same goroutine that reads from WebSocket. Since OnMessage callback blocked on RPC call then reading loop can not proceed to read RPC reply from server. Need to think what is the best way to deal with this.

**Comment by larry-dev** [comment]
@ZhuRongJian Hi,I try to modify the client.reader method to solve this problem, but I don't know what the impact will be.
![image](https://user-images.githubusercontent.com/18585750/80054956-205d8100-8553-11ea-8f09-52f9536aa20f.png)

**Comment by FZambia** [comment]
@larry-dev hi, this should solve a case, but this is a backwards incompatible change and can lead to races in existing user code since registered callbacks will be called from different goroutines. Also this can cause ordering problems in some cases.

**Comment by larry-dev** [comment]
@FZambia thx,i see. i use `go xxxx()` in my business method. 
`
OnMessage(.....){
 go test(xxx)
}
`

**Comment by FZambia** [comment]
@larry-dev what do you think about #31 ? This should resolve requirement to use separate goroutine inside handler.

**Comment by larry-dev** [comment]
@FZambia 👍,I use your code to check this problem is correct, I think very good.

**Comment by FZambia** [comment]
Released with v0.4.0
