### ISSUE TITLE
Publish messages

### ISSUE THREAD

**Issue by hound672** [centrifugal/centrifuge-go#45]
Hello.

https://github.com/centrifugal/cent
lib for python. Which can accept `api key` to publish messages.
Can `centrifuge-go` do this?
I cannot find this in docs or sources.

**Comment by FZambia** [comment]
The analogue of `Cent` lib for Go language is https://github.com/centrifugal/gocent - it allows to publish messages using server HTTP API.

`centrifuge-go` is client library for WebSocket connections.

Full list of server HTTP API libraries: https://centrifugal.github.io/centrifugo/libraries/api/
Full list of client (WebSocket) libraries: https://centrifugal.github.io/centrifugo/libraries/client/

**Comment by hound672** [comment]
Thanks!:)
