### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by maclof** [centrifugal/centrifuge-go#47]
Hey,

I can't seem to install this package at all, why is it trying to use protocol.Error if it doesn't implement the error interface?

λ go get github.com/centrifugal/centrifuge-go
# github.com/centrifugal/centrifuge-go
..\..\centrifugal\centrifuge-go\client.go:268:21: cannot use r.Error (type *protocol.Error) as type error in argument to fn:
        *protocol.Error does not implement error (missing Error method)
..\..\centrifugal\centrifuge-go\client.go:927:17: impossible type assertion:
        *protocol.Error does not implement error (missing Error method)
..\..\centrifugal\centrifuge-go\client.go:1053:37: cannot use r.Error (type *protocol.Error) as type error in argument to fn:
        *protocol.Error does not implement error (missing Error method)
..\..\centrifugal\centrifuge-go\client.go:1113:38: cannot use reply.Error (type *protocol.Error) as type error in argument to fn:
        *protocol.Error does not implement error (missing Error method)
..\..\centrifugal\centrifuge-go\client.go:1206:40: cannot use reply.Error (type *protocol.Error) as type error in argument to fn:
        *protocol.Error does not implement error (missing Error method)
..\..\centrifugal\centrifuge-go\client.go:1319:25: cannot use r.Error (type *protocol.Error) as type error in argument to fn:
        *protocol.Error does not implement error (missing Error method)
..\..\centrifugal\centrifuge-go\client.go:1366:25: cannot use r.Error (type *protocol.Error) as type error in argument to fn:
        *protocol.Error does not implement error (missing Error method)
..\..\centrifugal\centrifuge-go\client.go:1424:26: cannot use r.Error (type *protocol.Error) as type error in argument to fn:
        *protocol.Error does not implement error (missing Error method)
..\..\centrifugal\centrifuge-go\client.go:1486:31: cannot use r.Error (type *protocol.Error) as type error in argument to fn:
        *protocol.Error does not implement error (missing Error method)
..\..\centrifugal\centrifuge-go\client.go:1543:29: cannot use r.Error (type *protocol.Error) as type error in argument to fn:
        *protocol.Error does not implement error (missing Error method)
..\..\centrifugal\centrifuge-go\client.go:1543:29: too many errors

**Comment by FZambia** [comment]
Hello, thanks for raising an issue.

I think this should be fixed in `centrifuge-go` rather than in `protocol` package.

You can use `go mod` for dependency management - this way library will be installed properly loading the correct version of `protocol` package:
```console
❯ mkdir testapp
❯ cd testapp
❯ go mod init testapp
go: creating new go.mod: module testapp
❯ go get github.com/centrifugal/centrifuge-go@v0.6.5
go get: added github.com/centrifugal/centrifuge-go v0.6.5
❯ cat go.mod
module testapp

go 1.16

require github.com/centrifugal/centrifuge-go v0.6.5 // indirect
```

**Comment by FZambia** [comment]
Should be fixed now, most probably you need to pass `-u` flag to update package without using `go mod`

**Comment by FZambia** [comment]
@maclof hello, closing an issue, plz reopen if you find any problem installing an updated package
