### ISSUE TITLE
[Question/Feature request] Adding parameters to subscribe request for subscribe proxy

### ISSUE THREAD

**Issue by v1lev** [centrifugal/centrifuge-go#60]
Hello! Is there a way to add additional parameters to subscribe request? 
E.g. in the JS client I can do something like that:
```javascript
centrifuge.subscribe("public:channel", function(res) {
    console.log(res);
}, {
    data: {api_key: "some-key"}
});
```
And I will receive the same data in proxy handler.
I didn't find a way to send parameters in golang client. Did I miss something?

**Comment by FZambia** [comment]
@v1lev hello, this field was [just recently added](https://github.com/centrifugal/protocol/commit/77d4534c25b59f070ebcdb9a96ab8da4094312e2) to protocol, so only supported by `centrifuge-js` at the moment.

Will try to add this soon, or feel free to send pull request.

**Comment by FZambia** [comment]
This is supported by latest version - https://github.com/centrifugal/centrifuge-go/releases/tag/v0.9.0.

It works only with Centrifugo v4, I am not planning to backport support of `data` to previous versions. May accept PR and do the release though.
