### ISSUE TITLE
socket leaks in case of resubscription error

### ISSUE THREAD

**Issue by shilkin** [centrifugal/centrifuge-go#7]
https://github.com/centrifugal/centrifuge-go/blob/master/centrifuge.go#L525
It's not enough to close channel, we need to close connection. Otherwise we get a socket leak, because in case of resubscribe() failed we go to the next iteration and call doReconnect() again and again, and every time new connection will be created.

I faced with it when my "signer" backand was stopped, and client started a reconnection loop. After some time I saw an error messages about sockets was exeeded in the nginx proxy.

Actually, I fixed it in this manner: https://github.com/shilkin/centrifuge-go/blob/master/centrifuge.go#L530

**Comment by FZambia** [comment]
Hello! Thanks for report.

Just submitted pull request fixing this. I almost reproduced your solution - the only difference is that I don't change status in `close()` method - left it in `Close` method (I mean [this](https://github.com/centrifugal/centrifuge-go/pull/8/commits/362d2f7caf7f7ba535d3992e7ee7a5aff881a21c#diff-313cb8010cee4f7198eed8a7d5d16ed0R359)). Because when we reconnecting status should be RECONNECTING.

**Comment by shilkin** [comment]
I can't find any difference between states CLOSED and RECONNECTING. The only one place where we check if state is RECONNECTING is [here](https://github.com/centrifugal/centrifuge-go/blob/master/centrifuge.go#L391). In this part of code CLOSED and CONNECTING are the same.

Furthremore, when I removed state changing from private method close() to public Close() my reconnection loop became mad: reconnecting process start to create new conections without any timeout, which we make in ReconnectStrategy.

I didn't reaseach this behaviour yet.

**Comment by FZambia** [comment]
hmm, thanks, I also noticed that travis tests started to hang after my changes, but had no time to investigate this.

**Comment by FZambia** [comment]
So looks like I fixed tests, stiil don't understand why that test hanging reproduced only in travis but ran OK on my local machine. But now problem gone away. Also I checked reconnect example to see how reconnect interval behaves - looks ok for me.
