### ISSUE TITLE
centrifuge-go 0.9.3 matches centrifuge 0.18.4 right? god please

### ISSUE THREAD

**Issue by Edward923** [centrifugal/centrifuge-go#70]
centrifuge-go 0.9.3 matches centrifuge 0.18.4 right? god please

**Comment by FZambia** [comment]
Hello @Edward923 

From readme:

> The latest centrifuge-go is compatible only with the latest [Centrifugo](https://github.com/centrifugal/centrifugo) server (v4) and [Centrifuge](https://github.com/centrifugal/centrifuge) >= 0.25.0. For Centrifugo v2, Centrifugo v3 and Centrifuge < 0.25.0 you should use centrifuge-go v0.8.x.


So the answer is - no, the latest centrifuge-go must not be used with Centrifuge v0.18.4
