### ISSUE TITLE
0.8.3: Subscribe ignores StreamPosition option if not connected

### ISSUE THREAD

**Issue by powerman** [centrifugal/centrifuge-go#76]
Call `Subscribe(centrifuge.WithSubscribeSince(sp))` right after `Connect()` usually ignores `sp` because client is not connected yet.

**Comment by FZambia** [comment]
Hello @powerman. Merged #74 and released with v0.8.4. Many thanks! Unfortunately I don't have enough resources to concentrate on v0.8.x.
