### ISSUE TITLE
Trying to Unsubscribe() causes the program to crash

### ISSUE THREAD

**Issue by Hudayberdyyev** [centrifugal/centrifuge-go#81]
In the link below, we got a crash when centrifuge property equal to nil:
https://github.com/centrifugal/centrifuge-go/blob/af2f81792f41548ce89618b0637acc66499ad231/subscription.go#LL341C3-L341C3

Is there any way, to do this without crash ?! By example, return an error about centrifuge client is nil.
Maybe I didn't understand correctly whole logic of package, but any information about this would be helpful. 
If it's possible try to fix it, or if you allow i can do it. If it's impossible please explain it. 

Thanks in advance.

**Comment by FZambia** [comment]
Hello @Hudayberdyyev , please provide a program which reproduces this.

**Comment by Hudayberdyyev** [comment]
> 

Sure, it's simple example. 
```
package main

func main() {
	subscription := &centrifuge.Subscription{}
	if err := subscription.Unsubscribe(); err != nil {
		log.Printf("error occures: %v\n", err)
	}
	log.Printf("success")
}
```

Output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100f3c9d4]

```

**Comment by FZambia** [comment]
You should not create subscriptions this way, use Client.NewSubscription method to allocate new subscriptions - https://github.com/centrifugal/centrifuge-go/blob/af2f81792f41548ce89618b0637acc66499ad231/examples/chat/main.go#L98

This is actually a problem of current `centrifuge-go` API, but I suppose the only thing I can do here is adding a comment about proper usage to Subscription struct.

**Comment by Hudayberdyyev** [comment]
ok thanks for your help
