### ISSUE TITLE
timeout for publish on golang client (only)

### ISSUE THREAD

**Issue by heiningair** [centrifugal/centrifuge-go#91]
Hi,

I have an application consisting of multiple modules which need to communicate with each other. for the sake of simplicity lets assume there are only 2 modules: one of them is a js react application and the other one a golang one.

environment:

* centrifugo server
* react client app (client0)
* golang client app (client1)

as i dont need authentication for now, the following configuration is applied:

`{
  "token_hmac_secret_key": "<hmac_value>",
  "admin_insecure":true,
  "admin_secret": "<admin_secret>",
  "api_key": "<api_key>",
  "admin": true,
  "allowed_origins": ["*"],
  "client_insecure": true,
  "api_insecure": true,
  "websocket_message_size_limit":524288,
  "allow_subscribe_for_client":true,
  "log_level": "debug"
}
`

on both clients i can successfully connect and have 2 subscriptions each on the channels: "channel0" and "channel1"

**steps taken in the application:**

A message is sent from client0 (js) to client1 (golang) via subscription on "channel0" to which the client1 has a handler set up to.  
-> this works fine!

The handler then sends a message back to client0, but via "channel1" this time. 
-> this partially works!
-> It actually publishes the message to channel1 and the js client0 gets notified on "channel1" publications. But on the client1 side, it produces an "timeout" error after a few seconds for a reason i cant explain

<i>doing the same via the servers admin dashboard "Actions" tab it works correctly</i>

**my publish method**
(it breaks in the else block -> result, err = sub.Publish(ctx, []byte(payloadJson)) throws the timeout error)
```
func (c *CentrifugeManager) Publish(channel, event string, data model.Serializable) error {
	// transform the data to a json byte array
	dataJson, err := data.Serialize()
	if err != nil {
		log.Error("Error serializing data:", err)
		return err
	}

	// Create payload for centrifuge publication
	payload := model.CentrifugePayload{
		Event: event,
		Data:  dataJson,
	}

	// serialize the payload
	payloadJson, err := payload.Serialize()
	if err != nil {
		log.Error("Error serializing payload:", err)
		return err
	}

	// Set a timeout for the publish operation
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	var result centrifuge.PublishResult

	// check if subscription exists
	sub, ok := c.client.GetSubscription(channel)
	if !ok {
		log.Error("Subscription not found for channel " + channel)
		return fmt.Errorf("subscription not found for channel %s", channel)
	} else {
		result, err = sub.Publish(ctx, []byte(payloadJson))
		if err != nil {
			log.Error("Error publishing data:", err)
			return err
		}
	}

	// log the result object as string
	log.Debug("Publish result: ", result)

	return nil
}
```

Am I missing something? How can there be a timeout if the actual message gets successfully populated via the channel?

thanks for taking a look :)

**Comment by FZambia** [comment]
Hello @heiningair 

Check out readme - https://github.com/centrifugal/centrifuge-go?tab=readme-ov-file#callbacks-should-not-block, I think that's the reason.

**Comment by heiningair** [comment]
Hi @FZambia,

Thanks for pointing me there! That was it.
